# Generated by Django 3.0.3 on 2020-12-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('tran_date', models.DateTimeField()),
                ('tran_id', models.CharField(max_length=30)),
                ('val_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('store_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('card_type', models.CharField(max_length=50)),
                ('card_no', models.CharField(max_length=80)),
                ('currency', models.CharField(max_length=3)),
                ('bank_tran_id', models.CharField(max_length=80)),
                ('card_issuer', models.CharField(max_length=50)),
                ('card_brand', models.CharField(max_length=30)),
                ('card_issuer_country', models.CharField(max_length=50)),
                ('card_issuer_country_code', models.CharField(max_length=2)),
                ('currency_type', models.CharField(max_length=3)),
                ('currency_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi_instalment', models.PositiveIntegerField(blank=True, null=True)),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('value_a', models.CharField(blank=True, max_length=255, null=True)),
                ('value_b', models.CharField(blank=True, max_length=255, null=True)),
                ('value_c', models.CharField(blank=True, max_length=255, null=True)),
                ('value_d', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_level', models.PositiveIntegerField(blank=True, null=True)),
                ('risk_title', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
                ('gateway', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'SSLCOMMERZ Transaction',
                'verbose_name_plural': 'SSLCOMMERZ Transactions',
                'db_table': 'transaction_histories',
            },
        ),
    ]
