# Generated by Django 3.0.3 on 2021-01-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='base_fair',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='card_sub_brand',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='currency_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='store_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='verify_sign',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='verify_sign_sha2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='card_no',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='card_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
