# Generated by Django 3.0.3 on 2020-09-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_auto_20200913_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='job_max_salary',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='settings',
            name='job_min_salary',
            field=models.IntegerField(default=5000),
        ),
    ]