# Generated by Django 3.0.3 on 2020-11-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_auto_20200920_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='sms_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
