# Generated by Django 3.0.3 on 2020-11-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_settings_sms_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='sms_password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='sms_sid',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='sms_username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
