# Generated by Django 3.0.3 on 2020-11-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_auto_20201108_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='sms_password',
            new_name='sms_api_token',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sms_username',
        ),
    ]
