# Generated by Django 3.0.3 on 2020-11-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0023_auto_20201110_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='regular_member_apply_limit_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='regular_member_apply_limit_per_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='standard_member_apply_limit_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='standard_member_apply_limit_per_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
