# Generated by Django 3.0.3 on 2020-12-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_auto_20201122_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='android_app_latest_version',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='android_force_update_app_latest_version',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='ios_app_latest_version',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='ios_force_update_app_latest_version',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
