# Generated by Django 3.0.3 on 2020-12-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0025_auto_20201205_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='standard_member_payable_amount_per_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='standard_member_payable_amount_per_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
