# Generated by Django 3.0.3 on 2020-11-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20200914_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_system_generated',
            field=models.BooleanField(default=False),
        ),
    ]
