# Generated by Django 3.0.3 on 2020-10-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0057_auto_20201003_1659'),
        ('job', '0107_jobapplication_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('score', models.PositiveIntegerField()),
                ('is_notified', models.BooleanField(default=False)),
                ('job', models.ForeignKey(db_column='job', on_delete=django.db.models.deletion.PROTECT, to='job.Job')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro.Professional')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'db_table': 'job_recommendations',
            },
        ),
    ]
