# Generated by Django 3.0.3 on 2020-10-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0109_auto_20201006_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrecommendation',
            options={'verbose_name': 'Job Recommendation', 'verbose_name_plural': 'Job Recommendations'},
        ),
    ]
