# Generated by Django 3.0.3 on 2020-10-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0110_auto_20201006_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='job',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
