# Generated by Django 3.0.3 on 2020-10-24 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0057_auto_20201003_1659'),
        ('job', '0111_auto_20201017_1509'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobrecommendation',
            unique_together={('professional', 'job')},
        ),
    ]
