# Generated by Django 3.0.3 on 2020-10-27 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0112_companyregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationStatus',
            fields=[
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Company Registration Status',
                'verbose_name_plural': 'Company Registration Statuses',
                'db_table': 'registration_statuses',
            },
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='companyregistration',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='job.RegistrationStatus'),
            preserve_default=False,
        ),
    ]
