# Generated by Django 3.0.3 on 2020-10-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0112_jobviewlog'),
        ('job', '0112_auto_20201024_1001'),
    ]

    operations = [
    ]
