# Generated by Django 3.0.3 on 2020-10-27 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0113_auto_20201027_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregistration',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='job.RegistrationStatus'),
        ),
    ]
