# Generated by Django 3.0.3 on 2020-10-31 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0112_applicationcomment'),
        ('job', '0113_merge_20201024_1737'),
    ]

    operations = [
    ]
