# Generated by Django 3.0.3 on 2020-11-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0116_auto_20201107_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
