# Generated by Django 3.0.3 on 2020-12-13 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0120_jobquestionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobquestionanswer',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobquestionanswer',
            name='answer_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
