# Generated by Django 3.0.3 on 2021-01-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0120_jobquestionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecommendation',
            name='recommended_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
