# Generated by Django 3.0.3 on 2020-12-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0058_auto_20201104_1715'),
        ('job', '0124_auto_20201213_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobquestionanswer',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='job_companies', to='job.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobquestionanswer',
            name='question_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='job_questions', to='pro.Professional'),
            preserve_default=False,
        ),
    ]
