# Generated by Django 3.0.3 on 2020-12-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0125_auto_20201213_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobquestionanswer',
            name='answer_created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
