# Generated by Django 3.0.3 on 2020-12-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0126_jobquestionanswer_answer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobquestionanswer',
            name='answer_modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='jobquestionanswer',
            name='question_modified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
