# Generated by Django 3.0.3 on 2020-12-19 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0127_auto_20201215_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobQuestionAnswerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('job_question_answer', models.ForeignKey(db_column='job', on_delete=django.db.models.deletion.PROTECT, to='job.JobQuestionAnswer')),
            ],
            options={
                'db_table': 'job_question_answer_histories',
            },
        ),
    ]
