# Generated by Django 3.0.3 on 2020-12-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0128_jobquestionanswerhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobquestionanswer',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
