# Generated by Django 3.0.3 on 2020-09-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0107_jobapplication_is_approved'),
        ('pro', '0054_auto_20200908_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='job_search_preference',
            field=models.CharField(choices=[('LOOKING_FOR_OPPORTUNITIES', 'Looking'), ('OPEN_TO_BETTER_OPPORTUNITIES', 'Not looking but open'), ('NOT_INTERESTED', 'Not interested')], default='LOOKING_FOR_OPPORTUNITIES', max_length=30),
        ),
        migrations.AddField(
            model_name='professional',
            name='notification_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalskill',
            name='is_top_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProfessionalLocationPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.City')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='pro.Professional')),
            ],
            options={
                'db_table': 'professional_location_preferences',
            },
        ),
    ]
