# Generated by Django 3.0.3 on 2020-09-28 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0107_jobapplication_is_approved'),
        ('pro', '0054_auto_20200908_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentactivity',
            name='releted_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='job.Company'),
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='releted_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='job.Job'),
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='releted_professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro.Professional'),
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='updated_section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
