# Generated by Django 3.0.3 on 2020-09-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0055_auto_20200928_0957'),
        ('pro', '0055_auto_20200928_1008'),
    ]

    operations = [
    ]
