# Generated by Django 3.0.3 on 2020-10-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0056_merge_20200928_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionallocationpreference',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pro_location_preferences', to='pro.Professional'),
        ),
    ]
