# Generated by Django 3.0.3 on 2020-11-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0057_auto_20201003_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professional',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professional',
            name='mobile_verification_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
