# Generated by Django 3.0.3 on 2020-11-30 02:47

from django.db import migrations, models
import p7.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0058_auto_20201104_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='mobile_verification_number',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[p7.validators.check_valid_phone_number]),
        ),
    ]
