# Generated by Django 3.0.3 on 2020-12-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0059_professional_mobile_verification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='membership_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('STANDARD', 'Standard')], default='Regular', max_length=30),
        ),
    ]
