# Generated by Django 3.0.3 on 2020-12-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0060_professional_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='membership_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Standard', 'Standard')], default='Regular', max_length=30),
        ),
    ]
