# Generated by Django 3.0.3 on 2020-12-28 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('pro', '0061_auto_20201227_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='last_subscription_expire_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='last_subscription_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='SubscriptionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('subscription_duration', models.PositiveIntegerField()),
                ('subscription_duration_type', models.CharField(choices=[('YEARLY', 'Yearly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=30)),
                ('is_payment_successful', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('payment_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.TransactionHistory')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='pro.Professional')),
            ],
            options={
                'db_table': 'subscription_infos',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('invoice_id', models.CharField(max_length=64)),
                ('subscription_duration', models.PositiveIntegerField()),
                ('subscription_duration_type', models.CharField(choices=[('YEARLY', 'Yearly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=30)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='pro.Professional')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
    ]
