# Generated by Django 3.0.3 on 2021-01-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0062_auto_20201228_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='current_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='current_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
